/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TimeLock } from "./TimeLock";
export type { TimelockFactory } from "./TimelockFactory";
export * as factories from "./factories";
export { TimeLock__factory } from "./factories/TimeLock__factory";
export { TimelockFactory__factory } from "./factories/TimelockFactory__factory";
